### ISSUE TITLE
pip install error 

### ISSUE THREAD

**Issue by sunset1234321** [AlexIoannides/py-package-template#8]
ERROR: Could not find a version that satisfies the requirement py-template-project (from versions: none)
ERROR: No matching distribution found for py-template-project

**Comment by AronWater** [comment]
guess it is due to pypi  "Python :: 3.7"

I think it is also valid for the higher version.   I simply use python3.9 to pip install -e .  on this repo

**Comment by jfthuong** [comment]
You need to do pip install py-package-template as indicated on top of the Pypi page. This install sucessfully. The command to install is correct.

**Comment by AlexIoannides** [comment]
Fixed by #15
